apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: acc-address-by-cep-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: acc-address-by-cep-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /account/address
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /account/address
